version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: course-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./FindCourse:/var/www/html
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: course-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: courses
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3300:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel

  nginx:
    image: nginx:latest
    container_name: course-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./FindCourse:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

volumes:
  db_data:

networks:
  laravel:
    driver: bridge
